# Generated by Django 5.1.15 on 2026-06-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20)),
                ('tipo_evento', models.CharField(choices=[('confirmacion', 'Confirmación de cita'), ('recordatorio_24h', 'Recordatorio 24h'), ('recordatorio_2h', 'Recordatorio 2h'), ('listo_recoger', 'Listo para recoger'), ('encuesta', 'Encuesta post-servicio'), ('bajo_stock', 'Alerta bajo stock'), ('bienvenida', 'Bienvenida'), ('activacion', 'Activación de cuenta')], max_length=30)),
                ('destino', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_programacion', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('intentos', models.IntegerField(default=0)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='agenda.cita')),
            ],
            options={
                'ordering': ['-fecha_programacion'],
            },
        ),
    ]
