# Generated by Django 5.1.15 on 2026-06-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('es_insumo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida_grooming', 'Salida Grooming'), ('salida_venta', 'Salida Venta'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_tras', models.IntegerField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('sku_variante', models.CharField(max_length=60, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
        ),
    ]
