# Generated by Django 5.1.15 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('canal_notificacion', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('servicio', 'Servicio'), ('recomendacion', 'Recomendación'), ('alerta', 'Alerta'), ('cancelacion', 'Cancelación'), ('vacuna', 'Vacuna')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('tamanio', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('alergias', models.TextField(blank=True)),
                ('temperamento', models.CharField(choices=[('tranquilo', 'Tranquilo'), ('nervioso', 'Nervioso'), ('agresivo', 'Agresivo'), ('inquieto', 'Inquieto')], default='tranquilo', max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('restricciones', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='mascotas/perfil/')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaDueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_dueno_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('documento', models.FileField(blank=True, upload_to='mascotas/vacunas/')),
            ],
        ),
    ]
