# Generated by Django 5.1.15 on 2026-06-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mascotas.mascota'),
        ),
        migrations.AddField(
            model_name='mascotadueno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.cliente'),
        ),
        migrations.AddField(
            model_name='mascotadueno',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='duenos',
            field=models.ManyToManyField(related_name='mascotas', through='mascotas.MascotaDueno', to='mascotas.cliente'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota'),
        ),
        migrations.AlterUniqueTogether(
            name='mascotadueno',
            unique_together={('mascota', 'cliente')},
        ),
    ]
