# Generated by Django 5.1.15 on 2026-06-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaGrooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza_al_momento', models.CharField(blank=True, max_length=100)),
                ('tamanio_al_momento', models.CharField(blank=True, max_length=20)),
                ('temperatura_animal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estado_ingreso', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('consumido_inventario', models.BooleanField(default=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='agenda.cita')),
            ],
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mascotas/fotos/')),
                ('momento', models.CharField(choices=[('antes', 'Antes'), ('despues', 'Después')], max_length=10)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='grooming.fichagrooming')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_observacion', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='agenda.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='grooming.fichagrooming')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grooming.itemchecklisttemplate')),
            ],
            options={
                'unique_together': {('ficha', 'item')},
            },
        ),
    ]
