# Generated by Django 5.1.15 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('mantenimiento', 'Mantenimiento'), ('vacaciones', 'Vacaciones'), ('ausencia', 'Ausencia')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('duracion_real', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='agendada', max_length=20)),
                ('fecha_reprogramacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('precio_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadGroomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('intervalo_descanso', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Groomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('capacidad_simultanea', models.IntegerField(default=1)),
                ('horario_trabajo', models.JSONField(blank=True, default=dict)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_base_minutos', models.IntegerField(default=60)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('permite_doble_booking', models.BooleanField(default=False)),
                ('requiere_bloqueo_consecutivo', models.BooleanField(default=False)),
                ('factor_tamanio_raza', models.JSONField(blank=True, default=dict)),
                ('consumo_insumos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
