# Generated by Django 5.1.15 on 2026-06-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reprogramadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groomer',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadgroomer',
            name='groomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.groomer'),
        ),
        migrations.AddField(
            model_name='cita',
            name='groomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.groomer'),
        ),
        migrations.AddField(
            model_name='bloqueocalendario',
            name='groomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.groomer'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadgroomer',
            unique_together={('groomer', 'dia_semana')},
        ),
    ]
